language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
sudo: required
install:
  - pip install -r requirements.txt
  - pip install flake8
before_script:
  - flake8 vscale
script:
  - nosetests --with-coverage --cover-package=vscale
